### PR TITLE
Raw data expose

### PR DESCRIPTION
**Pull request by wandenberg**
Change some code to avoid unnecessary operations, and add a raw_data method to expose the image bitmap.
The idea is be possible to use this values to image processing, like resize, crop, compare images, ...

### CODE REVIEW

**Comment by masarakki** [comment]
thanks! please squash all.

**Comment by wandenberg** [comment]
Hi @masarakki 

Did you prefer that I do one pull request to each "feature"?
Or you prefer the squash?

**Comment by masarakki** [comment]
I want you to do pull requests to each feature.

**Comment by wandenberg** [comment]
split in pull requests #12, #13 and #14

**Pull request closed without merging**
